# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/1debit/DotProgressBarSpecs'

target 'DotProgressBarDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DotProgressBarDemo
  pod 'DotProgressBar', '~> 0.6.4'

  target 'DotProgressBarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DotProgressBarDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
